### ISSUE TITLE
Cant install this package

### ISSUE THREAD

**Issue by Surrogate-TM** [ThomasWinkel/VisioJsonExport#1]
When I try install this package with command `pip install visio-json-export`, I have not success…    

    ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python <4.0,>=3.12
    ERROR: Could not find a version that satisfies the requirement visio-json-export (from versions: none)
    ERROR: No matching distribution found for visio-json-export

**Comment by ThomasWinkel** [comment]
What Python version do you use?
py --version
The package requires >=3.12
At least that is my version. I guess it will also work with older version.
You can try:
pip install visio-json-export --ignore-requires-python

**Comment by Surrogate-TM** [comment]
Yes, my version is older: **3.11.5**

**Comment by Surrogate-TM** [comment]
> ignore-requires-python

This trick works. Thank you
